apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-eventstore
  name: grpc-eventstore
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 50052
  selector:
    app: grpc-eventstore
  type: ClusterIP