resources:
  - ../base
namePrefix: preprod-
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: apps
    patch: |-
      - op: replace
        path: /spec/template/spec/project
        value: preprod-apps
      - op: replace
        path: /spec/template/metadata/name
        value: '{{path.basename}}' #preprod-{{path.basename}}