resources:
  - ../base
namePrefix: preprod-
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: apps
    patch: |-
      - op: replace
        path: /spec/template/spec/project
        value: preprod-apps
      - op: replace
        path: /spec/template/metadata/namespace
        value: preprod-{{path.basename}} 
      - op: add
        path: /spec/template/spec/source
        value:
          repoURL: https://github.com/opicaud/monorepo.git
          targetRevision: HEAD
          path: '{{path}}'
          helm:
            valueFiles:
              - values-preprod.yaml
      - op: replace
        path: /spec/template/spec/destination/namespace
        value: preprod