apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-eventstore-api-config
data:
  config.yaml: |
    version: v2
    event-store:
      protocol: grpc
      host: {{ .Values.eventstore.host }}
      port: 80