apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-eventstore-api-config
data:
  config.yaml: |
    version: v2/beta
    event-store:
      protocol: grpc
      host: eventstore-grpc.default.svc.cluster.local
      port: 80