apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "shape-app-grpc.fullname" . }}-collector-sidecar
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: localhost:4317
          http:
            endpoint: localhost:4318
    processors:

    exporters:
      debug:
      {{- if .Values.openTelemetry.exporter.enabled }}
      otlp/exporter:
        endpoint: {{ .Values.openTelemetry.exporter.endpoint }}
        tls:
          insecure: true
      {{- end }}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          {{- if .Values.openTelemetry.exporter.enabled }}
          exporters: [debug, otlp/exporter]
          {{ else }}
          exporters: [debug]
          {{- end }}
