apiVersion: v1
kind: Job
metadata:
  name: "{{ include "shape-app-grpc.fullname" . }}-smoke-test"
  labels:
    {{- include "shape-app-grpc.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}-smoke-tests
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}_smoke_tests:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - "./cli_linux"
            - "--host=shape-app-grpc.default.svc.cluster.local"
            - "--port=80"
          imagePullPolicy: { { .Values.image.pullPolicy } }
      restartPolicy: Never
  backoffLimit: 2
