apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventstore_grpc.fullname" . }}
  labels:
    {{- include "eventstore_grpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50052
      protocol: TCP
      name: http
  selector:
    {{- include "eventstore_grpc.selectorLabels" . | nindent 4 }}
