resources:
  - ../base
namePrefix: prod-
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: apps
    patch: |-
      - op: replace
        path: /spec/generators/0
        value:
          list:
            elements:
              - name: eventstore
                chart: eventstore-grpc
                version: "1.3.1"
                repoUrl: "ghcr.io/opicaud"
              - name: shape-app
                chart: shape-app-grpc
                version: "1.4.1"
                repoUrl: "ghcr.io/opicaud"
      - op: replace
        path: /spec/template/spec/project
        value: prod-apps
      - op: replace
        path: /spec/template/metadata/name
        value: prod-{{.name}}
      - op: remove
        path: /spec/template/spec/source
      - op: add
        path: /spec/template/spec/sources
        value:
          - repoURL: '{{.repoUrl}}'
            chart: '{{.chart}}'
            targetRevision: '{{.version}}'
            helm:
              passCredentials: true
              valueFiles:
                - $values/apps/eventstore-grpc/values-prod.yaml
          - repoURL: https://github.com/opicaud/monorepo.git
            targetRevision: HEAD
            ref: values
      - op: replace
        path: /spec/template/spec/destination/namespace
        value: prod