resources:
  - ../base
namePrefix: prod-
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: apps
    patch: |-
      - op: replace
        path: /spec/template/spec/project
        value: prod-apps
      - op: replace
        path: /spec/template/metadata/name
        value: prod-{{path.basename}}