resources:
  - ../base
namePrefix: prod-
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: apps
    patch: |-
      - op: replace
        path: /spec/generators/0
        value:
          list:
            elements:
            - chart: eventstore-grpc
              version: "1.6.0"
              repoUrl: "ghcr.io/opicaud"
            - chart: shape-app-grpc
              version: "1.10.0"
              repoUrl: "ghcr.io/opicaud"              
      - op: replace
        path: /spec/template/spec/project
        value: prod-apps
      - op: replace
        path: /spec/template/metadata/name
        value: prod-{{.chart}}
      - op: remove
        path: /spec/template/spec/source
      - op: add
        path: /spec/template/spec/sources
        value:
          - repoURL: '{{.repoUrl}}'
            chart: '{{.chart}}'
            targetRevision: '{{.version}}'
            helm:
              passCredentials: true
              valueFiles:
                - $values/apps/{{.chart}}/values-prod.yaml
              releaseName: '{{.chart}}'
          - repoURL: https://github.com/opicaud/monorepo.git
            targetRevision: HEAD
            ref: values
      - op: replace
        path: /spec/template/spec/destination/namespace
        value: prod