apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/opicaud/monorepo.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: argocd
    spec:
      project: apps
      source:
        repoURL: https://github.com/opicaud/monorepo.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      ignoreDifferences:
        - group: "monitoring.coreos.com"
          kind: "ServiceMonitor"
          name: "observability-tempo-*"
          jsonPointers:
            - /spec/endpoints/0/relabelings
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
