prometheus-blackbox-exporter:
  serviceMonitor:
    targets:
      - name: shape-app-grpc
        url: http://shape-app-grpc.preprod.svc.cluster.local
      - name: eventstore-grpc
        url: http://eventstore-grpc.preprod.svc.cluster.local

kube-prometheus-stack:
  global:
    rbac:
      create: false
  crds:
    enabled: false
  defaultRules:
    create: true
  prometheusOperator:
    enabled: false
  grafana:
    rbac:
      create: true
    datasources:
      datasources.yaml:
        datasources:
          - name: Tempo
            type: tempo
            url: http://observability-tempo-query-frontend.preprod.svc.cluster.local:3100

