apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "observability.fullname" . }}-oltp
spec:
  mode: daemonset
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: observability-oltp-collector.default.svc.cluster.local:4317
          http:
            endpoint: observability-oltp-collector.default.svc.cluster.local:4318
    processors:

    exporters:
      debug:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug]