apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "observability.fullname" . }}-oltp
spec:
  mode: daemonset
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      debug:
      otlphttp:
        endpoint: http://observability-tempo-distributor.{{ .Release.Namespace }}.svc.cluster.local:4318
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug, otlphttp]