// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: app_shape.proto

package app

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShapesClient is the client API for Shapes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShapesClient interface {
	Create(ctx context.Context, in *ShapeRequest, opts ...grpc.CallOption) (*Response, error)
}

type shapesClient struct {
	cc grpc.ClientConnInterface
}

func NewShapesClient(cc grpc.ClientConnInterface) ShapesClient {
	return &shapesClient{cc}
}

func (c *shapesClient) Create(ctx context.Context, in *ShapeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/area_calculator.Shapes/create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShapesServer is the server API for Shapes service.
// All implementations must embed UnimplementedShapesServer
// for forward compatibility
type ShapesServer interface {
	Create(context.Context, *ShapeRequest) (*Response, error)
	mustEmbedUnimplementedShapesServer()
}

// UnimplementedShapesServer must be embedded to have forward compatible implementations.
type UnimplementedShapesServer struct {
}

func (UnimplementedShapesServer) Create(context.Context, *ShapeRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedShapesServer) mustEmbedUnimplementedShapesServer() {}

// UnsafeShapesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShapesServer will
// result in compilation errors.
type UnsafeShapesServer interface {
	mustEmbedUnimplementedShapesServer()
}

func RegisterShapesServer(s grpc.ServiceRegistrar, srv ShapesServer) {
	s.RegisterService(&Shapes_ServiceDesc, srv)
}

func _Shapes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShapesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/area_calculator.Shapes/create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShapesServer).Create(ctx, req.(*ShapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Shapes_ServiceDesc is the grpc.ServiceDesc for Shapes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shapes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "area_calculator.Shapes",
	HandlerType: (*ShapesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _Shapes_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app_shape.proto",
}
