// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.7
// source: shape-app/api/proto/app_shape.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShapeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shape      string    `protobuf:"bytes,1,opt,name=shape,proto3" json:"shape,omitempty"`
	Dimensions []float32 `protobuf:"fixed32,2,rep,packed,name=dimensions,proto3" json:"dimensions,omitempty"`
}

func (x *ShapeMessage) Reset() {
	*x = ShapeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_app_api_proto_app_shape_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShapeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeMessage) ProtoMessage() {}

func (x *ShapeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shape_app_api_proto_app_shape_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeMessage.ProtoReflect.Descriptor instead.
func (*ShapeMessage) Descriptor() ([]byte, []int) {
	return file_shape_app_api_proto_app_shape_proto_rawDescGZIP(), []int{0}
}

func (x *ShapeMessage) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *ShapeMessage) GetDimensions() []float32 {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

type ShapeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shapes *ShapeMessage `protobuf:"bytes,1,opt,name=shapes,proto3" json:"shapes,omitempty"`
}

func (x *ShapeRequest) Reset() {
	*x = ShapeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_app_api_proto_app_shape_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeRequest) ProtoMessage() {}

func (x *ShapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shape_app_api_proto_app_shape_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeRequest.ProtoReflect.Descriptor instead.
func (*ShapeRequest) Descriptor() ([]byte, []int) {
	return file_shape_app_api_proto_app_shape_proto_rawDescGZIP(), []int{1}
}

func (x *ShapeRequest) GetShapes() *ShapeMessage {
	if x != nil {
		return x.Shapes
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_app_api_proto_app_shape_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_shape_app_api_proto_app_shape_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_shape_app_api_proto_app_shape_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_app_api_proto_app_shape_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_shape_app_api_proto_app_shape_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_shape_app_api_proto_app_shape_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_shape_app_api_proto_app_shape_proto protoreflect.FileDescriptor

var file_shape_app_api_proto_app_shape_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x0c,
	0x53, 0x68, 0x61, 0x70, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x68, 0x61, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x61,
	0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x3b, 0x0a, 0x0c, 0x53, 0x68, 0x61, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x06, 0x73, 0x68, 0x61, 0x70, 0x65, 0x73, 0x22,
	0x34, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x32, 0x3a, 0x0a, 0x06, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x12, 0x30,
	0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f,
	0x70, 0x69, 0x63, 0x61, 0x75, 0x64, 0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x72, 0x65, 0x70, 0x6f, 0x2f,
	0x73, 0x68, 0x61, 0x70, 0x65, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shape_app_api_proto_app_shape_proto_rawDescOnce sync.Once
	file_shape_app_api_proto_app_shape_proto_rawDescData = file_shape_app_api_proto_app_shape_proto_rawDesc
)

func file_shape_app_api_proto_app_shape_proto_rawDescGZIP() []byte {
	file_shape_app_api_proto_app_shape_proto_rawDescOnce.Do(func() {
		file_shape_app_api_proto_app_shape_proto_rawDescData = protoimpl.X.CompressGZIP(file_shape_app_api_proto_app_shape_proto_rawDescData)
	})
	return file_shape_app_api_proto_app_shape_proto_rawDescData
}

var file_shape_app_api_proto_app_shape_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shape_app_api_proto_app_shape_proto_goTypes = []interface{}{
	(*ShapeMessage)(nil), // 0: proto.ShapeMessage
	(*ShapeRequest)(nil), // 1: proto.ShapeRequest
	(*Response)(nil),     // 2: proto.Response
	(*Message)(nil),      // 3: proto.Message
}
var file_shape_app_api_proto_app_shape_proto_depIdxs = []int32{
	0, // 0: proto.ShapeRequest.shapes:type_name -> proto.ShapeMessage
	3, // 1: proto.Response.message:type_name -> proto.Message
	1, // 2: proto.Shapes.create:input_type -> proto.ShapeRequest
	2, // 3: proto.Shapes.create:output_type -> proto.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shape_app_api_proto_app_shape_proto_init() }
func file_shape_app_api_proto_app_shape_proto_init() {
	if File_shape_app_api_proto_app_shape_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shape_app_api_proto_app_shape_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShapeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shape_app_api_proto_app_shape_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShapeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shape_app_api_proto_app_shape_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shape_app_api_proto_app_shape_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shape_app_api_proto_app_shape_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shape_app_api_proto_app_shape_proto_goTypes,
		DependencyIndexes: file_shape_app_api_proto_app_shape_proto_depIdxs,
		MessageInfos:      file_shape_app_api_proto_app_shape_proto_msgTypes,
	}.Build()
	File_shape_app_api_proto_app_shape_proto = out.File
	file_shape_app_api_proto_app_shape_proto_rawDesc = nil
	file_shape_app_api_proto_app_shape_proto_goTypes = nil
	file_shape_app_api_proto_app_shape_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShapesClient is the client API for Shapes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShapesClient interface {
	Create(ctx context.Context, in *ShapeRequest, opts ...grpc.CallOption) (*Response, error)
}

type shapesClient struct {
	cc grpc.ClientConnInterface
}

func NewShapesClient(cc grpc.ClientConnInterface) ShapesClient {
	return &shapesClient{cc}
}

func (c *shapesClient) Create(ctx context.Context, in *ShapeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Shapes/create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShapesServer is the server API for Shapes service.
type ShapesServer interface {
	Create(context.Context, *ShapeRequest) (*Response, error)
}

// UnimplementedShapesServer can be embedded to have forward compatible implementations.
type UnimplementedShapesServer struct {
}

func (*UnimplementedShapesServer) Create(context.Context, *ShapeRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterShapesServer(s *grpc.Server, srv ShapesServer) {
	s.RegisterService(&_Shapes_serviceDesc, srv)
}

func _Shapes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShapesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Shapes/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShapesServer).Create(ctx, req.(*ShapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shapes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Shapes",
	HandlerType: (*ShapesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _Shapes_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shape-app/api/proto/app_shape.proto",
}
