// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: app/proto/app_area_calculator.proto

package app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShapeMessageV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shape      string    `protobuf:"bytes,1,opt,name=shape,proto3" json:"shape,omitempty"`
	Dimensions []float32 `protobuf:"fixed32,2,rep,packed,name=dimensions,proto3" json:"dimensions,omitempty"`
}

func (x *ShapeMessageV2) Reset() {
	*x = ShapeMessageV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_app_area_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShapeMessageV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeMessageV2) ProtoMessage() {}

func (x *ShapeMessageV2) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_app_area_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeMessageV2.ProtoReflect.Descriptor instead.
func (*ShapeMessageV2) Descriptor() ([]byte, []int) {
	return file_app_proto_app_area_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *ShapeMessageV2) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *ShapeMessageV2) GetDimensions() []float32 {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

type AreaRequestV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shapes []*ShapeMessageV2 `protobuf:"bytes,1,rep,name=shapes,proto3" json:"shapes,omitempty"`
}

func (x *AreaRequestV2) Reset() {
	*x = AreaRequestV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_app_area_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreaRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaRequestV2) ProtoMessage() {}

func (x *AreaRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_app_area_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaRequestV2.ProtoReflect.Descriptor instead.
func (*AreaRequestV2) Descriptor() ([]byte, []int) {
	return file_app_proto_app_area_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *AreaRequestV2) GetShapes() []*ShapeMessageV2 {
	if x != nil {
		return x.Shapes
	}
	return nil
}

type AreaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []float32 `protobuf:"fixed32,1,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *AreaResponse) Reset() {
	*x = AreaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_app_area_calculator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaResponse) ProtoMessage() {}

func (x *AreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_app_area_calculator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaResponse.ProtoReflect.Descriptor instead.
func (*AreaResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_app_area_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *AreaResponse) GetValue() []float32 {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_app_proto_app_area_calculator_proto protoreflect.FileDescriptor

var file_app_proto_app_area_calculator_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x5f,
	0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x46, 0x0a, 0x0e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x02, 0x52, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x48,
	0x0a, 0x0d, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x32, 0x12,
	0x37, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x32,
	0x52, 0x06, 0x73, 0x68, 0x61, 0x70, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x0c, 0x41, 0x72, 0x65, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x61,
	0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x53, 0x0a, 0x10,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x56, 0x32,
	0x12, 0x1e, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x32,
	0x1a, 0x1d, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x32, 0x2f, 0x61, 0x72,
	0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70,
	0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_proto_app_area_calculator_proto_rawDescOnce sync.Once
	file_app_proto_app_area_calculator_proto_rawDescData = file_app_proto_app_area_calculator_proto_rawDesc
)

func file_app_proto_app_area_calculator_proto_rawDescGZIP() []byte {
	file_app_proto_app_area_calculator_proto_rawDescOnce.Do(func() {
		file_app_proto_app_area_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_proto_app_area_calculator_proto_rawDescData)
	})
	return file_app_proto_app_area_calculator_proto_rawDescData
}

var file_app_proto_app_area_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_proto_app_area_calculator_proto_goTypes = []interface{}{
	(*ShapeMessageV2)(nil), // 0: area_calculator.ShapeMessageV2
	(*AreaRequestV2)(nil),  // 1: area_calculator.AreaRequestV2
	(*AreaResponse)(nil),   // 2: area_calculator.AreaResponse
}
var file_app_proto_app_area_calculator_proto_depIdxs = []int32{
	0, // 0: area_calculator.AreaRequestV2.shapes:type_name -> area_calculator.ShapeMessageV2
	1, // 1: area_calculator.Calculator.calculateMultiV2:input_type -> area_calculator.AreaRequestV2
	2, // 2: area_calculator.Calculator.calculateMultiV2:output_type -> area_calculator.AreaResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_proto_app_area_calculator_proto_init() }
func file_app_proto_app_area_calculator_proto_init() {
	if File_app_proto_app_area_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_proto_app_area_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShapeMessageV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_app_area_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreaRequestV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_app_area_calculator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_proto_app_area_calculator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_proto_app_area_calculator_proto_goTypes,
		DependencyIndexes: file_app_proto_app_area_calculator_proto_depIdxs,
		MessageInfos:      file_app_proto_app_area_calculator_proto_msgTypes,
	}.Build()
	File_app_proto_app_area_calculator_proto = out.File
	file_app_proto_app_area_calculator_proto_rawDesc = nil
	file_app_proto_app_area_calculator_proto_goTypes = nil
	file_app_proto_app_area_calculator_proto_depIdxs = nil
}
