{
 "title": "Observability",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Availability Observability",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tempo_build_info", "legendFormat": "tempo-{{container}}" },
    { "expr": "prometheus_build_info", "legendFormat": "{{container}}" },
    { "expr": "grafana_build_info", "legendFormat": "{{ container }}" }
   ]
  },
  {
   "title": "Availability Services",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{ target }}" }
   ]
  },
  {
   "title": "Received spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "tempo_distributor_spans_received_total",
     "legendFormat": "__auto"
    },
    { "expr": "tempo_receiver_accepted_spans", "legendFormat": "{{__name__}}" },
    { "expr": "tempo_receiver_refused_spans", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}