---
name: monorepo
on:
  push:
    branches:
      - main
jobs:
  monorepo-job:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/bazel-public/bazel:5.4.0
      options: -e USER="root" -u="root"
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch bazel cache
        uses: actions/cache@v3
        with:
          path: /tmp/cache
          key: bazel-cache
          restore-keys: |
            bazel-cache
      - name: Bazel test
        run: bazel --output_user_root=/tmp/cache test --test_output=errors //...
      - name: Bazel release
        run: |
          for package in $(cat $(bazel --output_user_root=/tmp/cache cquery --ui_event_filters=-INFO //hack:find-what-packages-to-release --output=files))
          do
            bazel --output_user_root=/tmp/cache run $package":release_me"
          done
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}