---
name: Renovate PR Checks
on:
  pull_request:
    branches:
      - main
concurrency:
  group: renovate-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  bazel-tests:
    uses: ./.github/workflows/bazel-tests.yml
    permissions:
      contents: write
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
  enable-automerge:
    needs: bazel-tests
    if: github.actor == 'renovate[bot]' && contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
